# config/packages/doctrine_mongodb.yaml
doctrine_mongodb:
  connections:
    default:
      server: '%env(resolve:MONGODB_URL)%'
      options:
        username: linktree
        password: linktree
        db: linktree
  default_database: linktree
  document_managers:
    default:
      auto_mapping: true
      mappings:
        App:
          is_bundle: false
          type: annotation
          dir: '%kernel.project_dir%/src/Document'
          prefix: App\Document\
          alias: App
  fixture_loader: Symfony\Bridge\Doctrine\DataFixtures\ContainerAwareLoader