services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: linktree
    ports:
      - 27017:27017
    volumes:
      - ./mongodb-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data_container:/data/db
  php:
    container_name: php
    build:
      context: ./
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/linktree
    depends_on:
      - mongodb
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/linktree
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mongodb

volumes:
  mongodb_data_container: